# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 14:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restAPI.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentName', models.CharField(max_length=255)),
                ('startDate', models.DateField(default=datetime.date(2016, 9, 13))),
                ('dueDate', models.DateField(null=True, validators=[restAPI.models.is_before_today])),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=255)),
                ('classID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Class')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=255)),
                ('schoolID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolYear', models.PositiveSmallIntegerField(default=2016)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.School')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=255)),
                ('isDone', models.BooleanField(default=False)),
                ('startDate', models.DateField(default=datetime.date(2016, 9, 13))),
                ('endDate', models.DateField(null=True, validators=[restAPI.models.is_before_today])),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField()),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('schoolRoster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restAPI.SchoolRoster')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classroster',
            name='userInfo',
            field=models.ManyToManyField(to='restAPI.UserInfo'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.School'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='classFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.Class'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='userInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restAPI.UserInfo'),
        ),
    ]
